include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
    unawaited_futures: true
    always_declare_return_types: true
    prefer_final_locals: true
    avoid_empty_else: true
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
    avoid_relative_lib_imports: true
    no_duplicate_case_values: true
    prefer_spread_collections: true
    use_super_parameters: true

analyzer:
  errors:
    invalid_annotation_target: ignore
